sudo: false
language: ruby

addons:
  postgresql: "9.4"

rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head

gemfile:
 - Gemfile

before_install:
  - gem update bundler

before_script:
  - psql -U postgres -c "CREATE ROLE fluentd WITH LOGIN ENCRYPTED PASSWORD 'fluentd';"
  - psql -U postgres -c "CREATE DATABASE fluentd_test OWNER fluentd;"
  - wget https://dl.minio.io/server/minio/release/linux-amd64/minio
  - chmod +x minio
  - 2>/dev/null 1>/dev/null sudo ./minio server /minio&
  - wget https://dl.minio.io/client/mc/release/linux-amd64/mc
  - chmod +x mc
  - ./mc config host add minio http://127.0.0.1:9000 minioadmin minioadmin
  - ./mc mb minio/fluentd-test12345

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: ruby-head
